name: Publish to Maven Central

on:
  workflow_dispatch:

jobs:
  increment-version:
    name: Auto Increment Version
    uses: health-education-england/.github/.github/workflows/auto-version.yml@main
    secrets:
      commit-pat: ${{ secrets.PAT_AUTOMATED_COMMITS }}

  publish:
    name: Publish
    needs: increment-version
    runs-on: ubuntu-latest
    if: needs.increment-version.outputs.new-version

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: temurin
          java-version: 21

      - name: Publish
        run: ./gradlew publishToMavenLocal

      # Temporary step to allow verification of the built dependency.
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uk.nhs.tis.trainee_version-catalog_${{ needs.increment-version.outputs.new-version }}
          path: ~/.m2/uk/nhs/tis/trainee/version-catalog/${{ needs.increment-version.outputs.new-version }}/
