name: Publish to Maven Central

on:
  workflow_dispatch:
    inputs:
      force-publish-version:
        description: Skip versioning and force publish the given version instead. Should not include the `v` prefix (e.g `1.0.0`).
        required: false
        type: string

jobs:
  increment-version:
    name: Auto Increment Version
    uses: health-education-england/.github/.github/workflows/auto-version.yml@main
    if: ${{ !inputs.force-publish-version }}
    secrets:
      commit-pat: ${{ secrets.PAT_AUTOMATED_COMMITS }}

  publish:
    name: Publish
    needs: increment-version
    runs-on: ubuntu-latest
    if: |
      !failure() && !cancelled() &&
      (inputs.force-publish-version || needs.increment-version.outputs.new-version)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.force-publish-version || needs.increment-version.outputs.new-version }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          cache: gradle
          distribution: temurin
          java-version: 21

      - name: Publish
        run: ./gradlew publish --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_GPG_PASSPHRASE }}
